name: Jira Key Validation

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  validate-jira-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get recent commit messages
        run: |
          echo "Checking for Jira issue key in commit messages..."
          git log -1 --pretty=%B
          if ! git log -1 --pretty=%B | grep -E "[A-Z]{2,10}-[0-9]+"; then
          echo "Commit message does not contain a valid Jira key."
          exit 1
          fi

